:PROPERTIES:
:ID:       68568f9f-7b3f-4422-8c96-e472fc44b393
:END:
#+date: [2022-04-05 21:04]
#+hugo_lastmod: 2024-12-25 07:50:29 -0500
#+title: Email setup
#+filetags: :email:

This page describes how I used to read my [[id:aaaefce4-768c-4609-ade9-4c22e093e7aa][email]] on my Linux Mint box.

I use:
 * fetchmail
 * postfix
 * procmail

Basically, I use fetchmail to read my mail from various POP3/IMAP accounts.
Fetchmail will then deliver the email to a running postfix instance (vis
postfix's sendmail command).

I don't need any particular domain set up - user@localhost works.  When
installing postfix, I believe the "Internet with smarthost" option is what
you want.

Procmail is involved in the delivery process via my .forward file which
looks like this:

#+begin_src 
|/usr/bin/procmail
#+end_src

** Use of IMAP

I use Maildirs to store my email, but Gnus support for Maildirs is really
crappy.  Surprisingly, Gnus support for IMAP seems to be much better, to the
point where accessing my maildirs through a local IMAP server usually
produces better results than access my maildirs directly.

I use dovecot for my IMAP server.  Out of the box, it uses an authentication
scheme based of the user's login password.
