:PROPERTIES:
:ID:       0b228ecf-49f5-4f3f-8732-95edc5e21b4e
:END:
#+date: [2022-04-06 22:33]
#+hugo_lastmod: 2025-01-03 17:29:39 -0500
#+title: Beer tasting

My beer tasting page, where I collect information about various beers I've
tried.

My ratings system is my [[id:92A00B55-3CAE-4E37-8971-DA1A2184A54D][standard]] 4 star version.

Beer is broadly divided into lagers and ales; lagers are "bottom fermented"
or "cold fermented" while ales are "top fermented" or "warm fermented".
Ales are a much older style while lagers are a relatively recent invention.

While I find that broad distinction academically interesting, I find it's
not useful for guidance on whether I will like a particular beer.  Much more
useful is the colour (blond, amber, red, etc.) indicating how the malt is
toasted, and hop content, indicating how bitter the end product will be.
This informs how I categorize the beers I've tried.

 * [[id:955adb37-99eb-4cef-929d-698d9fcb8b6d][Blond lagers, ales, pilsners, etc.]]
 * [[id:9d43b8e2-613f-47d0-a5d4-275a1ee8962e][Pale ales, Enlish bitters, etc.]]
 * [[id:48628120-0934-4297-a064-5d03b62847db][Red ales, lagers, etc.]]
 * [[id:34f25681-cbcf-4b7e-a2ed-d2a0b2c6d2e1][Stouts, Porters, Dark lagers, etc.]]
 * [[id:ebe255e9-6553-4ebd-82a4-88e203e4c456][IPAs, APAs, etc.]]
 * [[id:9a70704c-417a-4f86-aa8f-bfec29d51e19][Scottish ales]]
