:PROPERTIES:
:ID:       E9DDE472-8D71-4547-992C-56D16AE6A5E5
:END:
#+title: Digital Garden

Welcome to my attempt at a [[https://maggieappleton.com/garden-history][digital garden]], a repository for notes, reviews,
recipes and whatever else strikes my fancy.  Think of it as a cross between
a digital scrapbook and a personal wiki.  The term "garden" is supposed to
be evocative of an actual, physical garden, with the attendant growing and
watering and weeding that comes with it.  [[https://maggieappleton.com][Maggie Appleton]] wrote a really
good [[https://maggieappleton.com/garden-history][article]] about it.

The garden metaphor is often contrasted with the stream metaphor, used to
describe more traditional blogs which house timestamped, serialized content.
I have [[https://desmondrivet.com/posts/lifestream][one of those]], too (housed on a [[https://desmondrivet.com][website]] where you can find out more
[[https://desmondrivet.com/about][about me]] if you wish).  More information about the distinction between these
different kinds of websites can be found in the [[https://desmondrivet.com/2020/05/01/wikis-and-blogs][article]] I wrote on the
subject.

In the past I maintained a wiki based on [[id:0EC8EBA9-030B-4337-8019-3525049D6F79][MoinMoin]], which sort of filled the
niche of what I'm trying to accomplish here.  It was bascially a personal
knowledge base.  It got hacked and I eventually stopped using it, partially
because I wanted a purely text based one that I could edit with [[id:e8f63911-0c0b-4f37-9aed-b2e415144f9d][Emacs]].

I've recently started experimenting with [[id:5942bb24-580d-49b6-a941-28c172b4d7b5][org-roam]] for this kind of stuff,
even if I'm not totally sold on the finicky zettelkaten aspect of it.

** Text based garden

I like the idea of maintaining this wiki/garden as I do my blog - in [[id:a2e09732-e1f9-4e01-a5fa-74092ae75cd5][text]],
using a CM system like github to trigger publication.

** Motivation

I read a fair bit, but I forget a lot of what I read.  I learn a lot in my
day to day life, at my job, etc. but I have a tendency to forget what I
learn.  One weakness I have is that my memory isn't very good, especially
when it's adhoc knowledge.

My hope is that a digital garden can help me in this regard.  Writing out a
literature or permanent note for each book I read might help me rememeber
what I got out of it.
