:PROPERTIES:
:ID:       fe77c5b6-6af8-4a89-9c75-66ab6e299b6a
:END:
#+date: [2025-08-29 Fri 16:37]
#+hugo_lastmod: [2025-08-29 Fri 16:37]
#+title: Gingerbread (Kitchen Nelly's Vsersion)
#+filetags: :dessert:cake:ginger:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Not as densely sweet as some other gingerbreads.  More bready, less
cakey. Good with ice cream.

Source: http://www.kitchenelly.com/2010/03/a-reliable-weapon-gingerbread/

Yield: 20 servings

** Ingredients

 * 1/4 pound (1 stick) unsalted butter
 * 1 cup sugar
 * 2 eggs
 * 3/4 cup molasses
 * 3/4 cup boiling water
 * 2 1/2 cups unbleached, all-purpose flour
 * 2 teaspoons baking soda
 * 1/2 teaspoon salt
 * 2 teaspoons ground ginger
 * Powdered sugar
 * Whipping cream
 * Dark chocolate

** Instructions

Preheat the oven to 350°F. Butter and lightly flour a 9-inch round (or
8-inch square) cake pan.

Cream the butter. Add the sugar and beat together until light.

Add the eggs and beat well. Add the molasses, then the boiling water and
blend.  Use the molasses measuring cup for the hot water to capture any
molasses that clings to the cup.

Add the flour, soda, salt, and ginger to the batter and blend until
combined.

Pour the batter into the prepared pan.

Bake at 350°F for 45 to 55 minutes, or until a skewer inserted in the middle
comes out clean. Cool in the pan for 5 minutes.

Invert onto a cake rack.

Cool another few minutes before sprinkling with sugar. Begin with a light
coating of powdered sugar, sprinkled through a fine-mesh sieve.

Place a stencil over the cake and sprinkle heavily through the cuts.

Serve warm with lightly sweetened and softly whipped heavy cream, and grate
a little dark chocolate on top.
