:PROPERTIES:
:ID:       18d43274-350a-4664-b892-dffb955dcf5d
:END:
#+date: [2025-08-30 Sat 15:48]
#+hugo_lastmod: [2025-08-30 Sat 15:48]
#+title: Orzo Salad
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Good for a light summer lunch

Source: https://www.loveandlemons.com/orzo-salad/

Yield: 6 servings

** Ingredients

 * 1 1/2 cups dry orzo pasta
 * 1 recipe [[id:bf3daf77-467f-44d4-a75d-e3ee9c8f03c9][Greek Salad Dressing]]
 * 1 tablespoon red wine vinegar
 * 1 tablespoon fresh lemon juice
 * 1/2 teaspoon oregano
 * 1/2 teaspoon sea salt
 * 2 Persian cucumbers, halved vertically, and sliced ¼-inch thick
 * 2 cups halved cherry tomatoes
 * 1 cup cooked chickpeas, drained, and rinsed
 * 4 ounces feta cheese, cut into ¼-inch cubes
 * 1/3 cup thinly sliced red onion
 * 1/2 cup pitted Kalamata olives
 * 1 cup fresh basil and/or mint leaves
 * Freshly ground black pepper
  
** Instructions

Bring a large pot of salted water to a boil. Prepare the pasta according to
the package directions, or until slightly past al dente. Drain the orzo and
toss it with a little olive oil, so that it doesn’t stick together. Spread
onto a baking sheet to cool.

Prepare the Greek Salad Dressing and add in the red wine vinegar, lemon
juice, oregano, and sea salt.

In a large bowl, toss together the cooked orzo, cucumbers, tomatoes,
chickpeas, feta, red onion, and olives. Drizzle the dressing over the salad,
add half the herbs, season with freshly ground black pepper, and toss to
coat. Garnish with the remaining herbs and serve.
