:PROPERTIES:
:ID:       92715a0a-4d20-4d00-a43d-980774046f09
:END:
#+date: [2025-08-30 Sat 08:35]
#+hugo_lastmod: [2025-08-30 Sat 08:35]
#+title: Hoppin' John (Pioneer Woman Version)
#+filetags: :black-eyed-peas:vegetarian:vegan:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This version of Hoppin' John uses a lot more peas than mine, so it's less
soupy.  Omit ham hock for vegetarian, use vegetable broth.

Source: https://www.thepioneerwoman.com/food-cooking/recipes/a10902/hoppin-john/

Yield: 10 servings

** Ingredients

 * 4 Tablespoons Butter
 * 1 whole Large Onion, Diced
 * 4 cloves Garlic, Minced
 * 1 whole Green Bell Pepper, Diced
 * 2 stalks Celery, Diced
 * 4 cups Soaked Black-eyed Peas
 * 5 cups Low-sodium (or No-sodium) Chicken Broth
 * 1 whole Ham Hock
 * Salt And Pepper, to taste
 * Cayenne pepper, to taste
 * 2 tbsp. white vinegar

** Instructions

Soak black-eyed peas in cool water for at least 6 hours. Rinse before using.

Heat butter in a large pot over medium-high heat. Add onion, garlic, green
pepper, and celery and stir. Cook for 3 to 4 minutes. Stir in soaked beans,
then add chicken broth and ham hock as well as salt, pepper, and cayenne to
taste. Bring to a boil, then reduce heat and cover the pot for 30 minutes.

After 30 minutes, check the liquid level; if it's too soupy, cook with the
lid off for another 15 minutes or so. If it's too thick, splash in a little
more broth. Stir in vinegar, then taste for seasonings. Add more spice if
needed.

Serve over white or brown rice, making sure to get plenty of the cooking
liquid spooned over the top. Or, you may mix the bean mixture with the rice
before serving.

Variations: Add red bell pepper, canned diced tomatoes, diced jalapeños,
diced ham (instead of ham hocks), or sliced bacon (instead of ham
hocks). Stir in torn-up kale when 5 minutes of cooking time remain. You can
also use canned, drained black-eyed peas if preferred. Just use diced ham
instead of ham hock and a little less broth, as peas won't need to cook as
long.

