:PROPERTIES:
:ID:       bf9d41f1-435f-4559-b322-7d32b988b28c
:END:
#+date: [2025-08-12 Tue 20:01]
#+hugo_lastmod: [2025-08-12 Tue 20:01]
#+title: Buttermilk Biscuits
#+filetags: :sides:breakfast:vegetarian

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Source: http://www.food.com/recipe/southern-buttermilk-biscuits-26110

Duration: 22 minutes

Good, reliable recipe for buttermilk biscuits.  If you have a clean surface
ready to go, these are fairly quick to make.

** Ingredients:
 * 2 cups unbleached all-purpose flour, plus more for dusting the board (if you can get 
  White Lily flour, your biscuits will be even better)
 * 1/4 teaspoon baking soda
 * 1 tablespoon baking powder (use one without aluminum)
 * 1 teaspoon kosher salt or 1 teaspoon salt
 * 6 tablespoons unsalted butter, very cold
 *3/4 cup buttermilk (approx)

** Instructions

Preheat your oven to 450°F.

Combine the dry ingredients in a bowl, or in the bowl of a food processor.
    
Cut the butter into chunks and cut into the flour until it resembles course
meal.
    
If using a food processor, just pulse a few times until this consistency is

Add the buttermilk and mix JUST until combined.
    
If it appears on the dry side, add a bit more buttermilk.
    
Turn the dough out onto a floured board.
    
Gently, gently PAT (do NOT roll with a rolling pin) the dough out until it's
about 1/2" thick.
    
Use a round cutter to cut into rounds.
    
You can gently knead the scraps together and make a few more, but they will
not be anywhere near as good as the first ones.
     
Place the biscuits on a cookie sheet- if you like soft sides, put them
touching each other.
     
If you like"crusty" sides, put them about 1 inch apart- these will not rise
as high as the biscuits put close together.
     
Bake for about 10-12 minutes- the biscuits will be a beautiful light golden
brown on top and bottom.
     
Do not overbake.
     
Note: The key to real biscuits is not in the ingredients, but in the
handling of the dough.
     
The dough must be handled as little as possible or you will have tough
biscuits.
     
I have found that a food processor produces superior biscuits, because the
ingredients stay colder and there's less chance of overmixing.
     
You also must pat the dough out with your hands, lightly.
     
Rolling with a rolling pin is a guaranteed way to overstimulate the gluten,
resulting in a tougher biscuit.
     
Note 2: You can make these biscuits, cut them, put them on cookie sheets and
freeze them for up to a month.
     
When you want fresh biscuits, simply place them frozen on the cookie sheet
and bake at 450°F for about 20 minutes.
