:PROPERTIES:
:ID:       1d936efe-da91-4265-8822-c490b283f0b0
:END:
#+date: [2025-06-27 Fri 21:22]
#+hugo_lastmod: [2025-06-27 Fri 21:22]
#+title: Apple Cheddar French Toast
#+filetags: :apples:breakfast:vegetarian:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This one is a crowd pleaser and good for brunch.

Source: http://www.cbc.ca/inthekitchen/2011/10/apple-and-cheddar-french-toast.html

Yield: 4 servings

** Ingredients

 * 2 apples, peeled and diced
 * Butter
 * 1/2 tsp. cinnamon
 * 2 eggs
 * 3/4 cup milk
 * 1 loaf brioche bread (day old)
 * 1/2 cup grated aged cheddar
 * Icing sugar, for serving
 * Maple syrup, for serving

** Instructions

In a small skillet over medium heat, sauté the apples in 1 to 2
tbsp. butter. Add cinnamon and cook apples until tender and golden, about 5
to 7 minutes. Set aside.

Beat eggs and milk together in a shallow baking dish or bowl. Set aside.

Cut bread into 8 thick slices.

Spoon the apples evenly over 4 of the bread slices. Then sprinkle evenly
with cheddar cheese. Sandwich with remaining slices.

Dip each French toast sandwich into the egg mixture until evenly soaked.

Heat griddle to medium heat. (Alternatively, cook French toast in batches
using a large skillet.) Add 2 tbsp. butter. When butter melts, add the
French toast sandwiches. Cook until golden brown and crisp on both sides and
cheese is melted, about 3 to 4 minutes per side.

If needed, keep French toast warm in a 250 degree F. oven. Serve with a
dusting of icing sugar and drizzle of maple syrup.
