:PROPERTIES:
:ID:       28ab7f17-5a08-4c00-8ecc-3b3920505fbd
:END:
#+date: [2025-11-09 Sun 18:35]
#+hugo_lastmod: [2025-11-09 Sun 18:35]
#+title: Butterscotch Pie
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Basically homemade butterscotch pudding in a pie crust.  Delicious, exceeded my expectations.

Source: https://www.savingdessert.com/butterscotch-pie/

Yield: 8 servings

** Ingredients

 * 1 9-inch baked pie crust (recipe below)
 * 8 tablespoons unsalted butter
 * 1 cup dark brown sugar, packed
 * 1 cup boiling water
 * 3 tablespoons cornstarch
 * 2 tablespoon all-purpose flour
 * 1/2 teaspoon salt
 * 1 2/3 cups milk
 * 3 egg yolks
 * 1 teaspoon pure vanilla extract
 * (optional) 1/2 cup chopped pecans
   
*** For the topping:
 * 1 cup heavy whipping cream
 * 2 tablespoons powdered sugar
 
** Instructions

1. Place the egg yolks in a small mixing bowl. Whisk lightly. Set aside.

1. In a medium, heavy bottom good saucepan combine the cornstarch, flour,
   and salt. Whisk in the milk until blended. Set aside.
   
1. In a large light-colored skillet melt the butter over medium/low heat and
   cook stirring constantly until it turns nutty brown in color. (see note)
   Gradually add the dark brown sugar. Cook, stirring constantly, until it
   is melted, about 5 minutes. Carefully add 1 cup of boiling water. This is
   like making caramel as the mixture will sputter and spit.

1. Add the brown sugar mixture to the saucepan with the milk and flour. Heat
   over medium-low heat, stirring constantly until it begins to boil. This
   could take 10-15 minutes. Keep stirring.

1. Once the mixture has thickened, remove from the heat. Drizzle spoonfuls
   of the hot butterscotch into the egg yolks while whisking
   constantly. Repeat until you have added ⅓ of the butterscotch to the egg
   yolks.

1. Pour the egg mixture into the saucepan with the remaining butterscotch
   and return to the heat.

1. Cook, stirring constantly, until the mixtures begins to boil. Cook for
   another minute then remove from the heat and stir in the vanilla.

1. I using, place the chopped pecans at the bottom of the pie crust, then
   pour the custard into the pre-baked pie shell. Cool then refrigerate
   until ready to serve.

1. To make the topping whisk the heavy cream until soft peaks form. Add the
   confectioners sugar a little at a time and whisk until thickened. Dollop
   the whipped cream on top of the pie then add chopped cashews.
