:PROPERTIES:
:ID:       205f07bc-16d9-43de-ad84-37baba9a76a7
:END:
#+date: [2025-12-15 Mon 08:41]
#+hugo_lastmod: [2025-12-15 Mon 08:41]
#+title: Toffee
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Crunchy, sweet and buttery.  The only changes I made was using brown sugar
instead of white, using semi sweet chocolate chips instead of milk
chocolate, and toasting the nuts beforehand.

Source: https://preppykitchen.com/toffee/

Yield: 20 pieces

** Ingredients

 * 1 cup chopped pecans
 * 1 cup unsalted butter 226g
 * 1 cup granulated sugar 200g
 * 1/4 cup water
 * 1/2 tsp kosher salt
 * 1 tsp vanilla extract
 * 1 cup milk chocolate chips
 * 3 tbsp finely chopped pecans for the topping, plus sea salt if desired 

** Instructions

 1. Line a 9x9 inch baking dish with parchment paper then sprinkle the
    bottom evenly with chopped pecans and set aside.

 1. Add the sugar, water, salt and butter to a heavy-bottomed pot. Place
    over medium heat and bring to a boil, stirring frequently.
    
 1. Once boiling stir occasionally until the mixture reaches 300F, which is
    the hard crack stage.
    
 1. Remove from heat and carefully stir in the vanilla then immediately pour
    over the chopped pecans. Use a spatula to spread to the edges into a
    flat layer then set aside to cool slightly for about 2 minutes.
    
 1. Sprinkle chocolate chips over the top  and cover with foil for 4 minutes
    so the  chocolate chips soften.  Use a  spatula to spread  the chocolate
    into a thin layer then sprinkle with  finely chopped pecans and a bit of
    sea salt if desired.
    
 1. Refrigerate for at least an hour before lifting from baking dish and
    breaking into pieces. You can score the top with a knife then snap into
    pieces for a cleaner look.

** Notes

 * Toasting nuts is always a nice way to bring out more depth of
   flavor. Spread the chopped pecans on a baking sheet and bake at 350F for
   about 4 minutes or until fragrant.

 * You can sub in toasted chopped almonds for the pecans if desired.
    
 * A candy thermometer makes this such an easy recipe to make, do yourself a
   favor and pick one up if you don't have one yet.
   
 * Store toffee in an airtight container in a cool place. Humidity will make
   the toffee sticky while heat will melt the chocolate.
   
 * The chocolate is optional. You can leave it out or use 1/2 a cup instead
   for a paper thin layer. Milk, semisweet or bittersweet are all fine, it's
   really up to your personal preference.
   
 * I love this when topped with a sprinkle of big flaked sea salt, you can
   find Maldon's sea salt at most grocery stores or look for a brand that
   says fleur de sel.
