:PROPERTIES:
:ID:       df9767c2-f4f9-4ff9-9bf8-73ee5eb2014d
:END:
#+date: [2025-08-31 Sun 09:55]
#+hugo_lastmod: [2025-08-31 Sun 09:55]
#+title: Tourtiere
#+filetags: :pie:beef:pork:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

The classic French-Canadian meat pie.

Source: http://www.simplebites.net/how-to-makeclassic-tourtiere-qubec-pork-pie/

Yield: 2 9-inch pies

** Ingredients

 * 2 1/2 pounds ground pork (or beef, or a mix), ideally organic & local
 * 1 1/2 cups cold water
 * 1 cup finely chopped onion (about 1 medium onion)
 * 1/2 cup finely chopped celery (about 1 stalk)
 * 1 teaspoon ground black pepper
 * 2 bay leafs
 * 1 teaspoon dried savory
 * 1/2 teaspoon dried rosemary
 * 1/2 teaspoon grated nutmeg
 * 1/2 teaspoon cinnamon
 * Salt
 * 1/2 cup old-fashioned rolled oats
 * Pastry for two double-crust, 9-inch pies
 * 1 egg, beaten, for glaze

** Instructions

In a large, heavy frying pan, combine pork with cold water and heat to
boiling point. It should be slightly soupy.
 
Add onion, celery, pepper, bay leaf, savory, rosemary, nutmeg and
cinnamon. Cook, covered, over medium-low heat for 1 1/4 hours; stir
often. Add more water if mixture dries out.
 
Halfway through cooking time, season with salt to taste.
 
Stir in rolled oats and cook, stirring, for 1 to 2 minutes. Remove bay leaf
and allow to cool. Setting the entire pot in the snow bank speeds up this
process!
 
Meanwhile, line two 9-inch pie plates with pastry. When meat mixture is
lukewarm, divide it between two pie shells and spread it out evenly.
 
Brush around outer edge of pastry with the beaten egg. Place top crust on
the tart and press gently around the edge to seal. Trim pastry, crimp edges
and cut steam vents in top crust. Decorate as desired.
 
Bake in preheated 425°F oven for 15 minutes, then reduce heat to 375°F and
bake another 25 minutes or until crust is golden.
