:PROPERTIES:
:ID:       2aeeeac5-6ecf-45be-b0ef-7cee6f61f6b0
:END:
#+date: [2025-08-30 Sat 15:37]
#+hugo_lastmod: [2025-08-30 Sat 15:37]
#+title: Misir Wat (Ethiopian Spiced Lentils)
#+filetags: :lentils:vegetarian:ethiopian:
  
[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This is one of my favourite lentil dishes.  Absolutely delicious, even if
you don't have niter kibbeh.

Source: https://www.daringgourmet.com/misir-wat-ethiopian-spiced-red-lentils/

Yield: 6 servings

** Ingredients

 * 4 tablespoons niter kibbeh, divided
 * 1 large yellow onion, very finely diced
 * 3 cloves garlic, finely minced
 * 1 Roma tomato, very finely chopped
 * 3 tablespoons tomato paste
 * 2 tablespoons bebere (homemade strongly recommended), divided
 * 1 cup red lentils, rinsed
 * 2 1/2 cups Aneto All-Natural Chicken Broth (vegetarians use Aneto Vegetable Broth)
 * 1 teaspoon salt

** Instructions

Note: If you don't have niter kibbeh, you can just use butter with 1/4 cumin
or extra berbere.

Melt 3 tablespoons of the niter kibbeh in a medium stock pot.  Add the
onions and cook over medium-high heat for 8-10 minutes until golden brown.

Add the garlic, tomatoes, tomato paste and 1 tablespoon of the berbere and
cook for 5-7 minutes. Reduce the heat if needed to prevent burning.

Add the lentils, broth and salt, bring it to a boil, reduce the heat to low
and cover and simmer the lentils, stirring occasionally, for 40 minutes
(adding more broth if needed) or until the lentils are soft.

Stir in the remaining tablespoon of niter kibbeh and berbere. Simmer for a
couple more minutes. Add salt to taste.

Serve with Ethiopian injera.
