:PROPERTIES:
:ID:       800c4d09-6848-42ba-8d04-d7e56055d82e
:END:
#+date: [2025-08-31 Sun 09:39]
#+hugo_lastmod: [2025-08-31 Sun 09:39]
#+title: Sour Cream Coffee Cake
#+filetags: :dessert:cake:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This one came with a baking pan I bought.  Easy and tasty.

Yield: 24 servings

** Ingredients

*** Cake
 * 3 cups all-purpose flour
 * 1 1/4 cups granulated sugar
 * 1 1/2 teaspoons baking powder
 * 1 1/2 teaspoons baking soda
 * 3/4 teaspoon cinnamon
 * 1/4 teaspoon salt
 * 1 1/2 cups light sour cream
 * 3/4 cup vegetable oil
 * 3 eggs
 * 1 1/2 teaspoons vanilla extract
 * 3 tablespoons milk

*** Streusel
 * 2 teaspoons butter, softened
 * 1/2 cup brown sugar
 * 1/2 cup chopped pecans
 * 1 teaspoon cinnamon

** Instructions

In small bowl, cut butter in with sugar, pecans and cinnamon.  Set aside.

Preheat oven to 350F.  Spray 13x9 Oblong Cake Pan with vegetable pan spray.
Combine flour, sugar, baking power, baking soda, cinnamon, and salt in large
bowl.  Combine sour cream, oil, eggs, vanilla and milk.  Add to dry
ingredients.  Stir only to combine.  Pour batter into prepared pan.
Sprinkle streusel topping over mixture.

Bake 30-35 minutes or until golden brown and toothpick inserted in middle
comes out clean.  Cool on rack.  Serve warm or at room temperature.

