:PROPERTIES:
:ID:       c6c48845-20e8-4279-85f8-45bd9e650829
:END:
#+date: [2025-08-29 Fri 16:24]
#+hugo_lastmod: [2025-08-29 Fri 16:24]
#+title: Crustless Swiss Chard Quiche
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

#+attr_html: :alt Crustless swish chard quiche
#+attr_html: :width 800
#+attr_html: :class figure
https://media.desmondrivet.com/96/29/ae/7e/cdfd48838e8e5e0b68180038d1e949c028ccafd359a5a1fb653fc20e.jpg

Good way to use up a bunch of chard I sometimes get in my grocery
basket. Basically a baked omelette.  Good with a salad.

Source: https://www.food.com/recipe/crustless-swiss-chard-quiche-311434

Yield: 6 servings

** Ingredients

 * 1 teaspoon olive oil
 * 1/2 sweet onion
 * 1/2 bunch swiss chard
 * 2 1/2 cups shredded cheese
 * 4 eggs
 * 1 cup skim milk

** Instructions

Preheat oven to 375 degrees.

Wash and dry swiss chard. Cut off the very ends of the stems. Roughly chop
(leaving stems intact) the chard.

Add onion and Chard to the oil and saute until stems are tender (do not
overcook). Add salt & pepper to taste.

Meanwhile, grate 2.5 cups of cheese. Use whatever varieties you
want/have. Be creative! I used Swiss, Cheddar, Parmesan, and Cojito.

Wisk eggs. Add milk and cheese. Fold in the onion/chard mixture. Add salt &
pepper to taste, if necessary.

Pour into a pie dish that has been sprayed with nonstick cooking spray.

Bake for 35-45 minutes or until golden brown and no liquid seeps when you
poke it with a knife.
