:PROPERTIES:
:ID:       73cccf57-a6af-43dc-afbb-41ca29dbce48
:END:
#+date: [2025-09-21 Sun 16:28]
#+hugo_lastmod: [2025-09-21 Sun 16:28]
#+title: Org Books Notes

This is an [[id:e8f63911-0c0b-4f37-9aed-b2e415144f9d][Emacs]] package for managing reading lists in [[id:FA31BDBE-5F87-4DEE-ABE2-D8AFD52F7D03][Org Mode]].
Source code on [[https://github.com/lepisma/org-books][Github]].

Doesn't work very well:

 * Claims to support Amazon, Goodreads and [[id:fc68e2a2-2b53-43ea-865a-4eb8d7877eb3][Open Library]] URLs, Open Library
   only works when you use the Legacy Books API JSON URL.

 * Inserts the URL provided as a properties field which doesn't look nice
   when exported.

 * Doesn't insert the cover anywhere.

 * You can insert books via ISBN, but this is implemnted in terms of Open
   Library, with the aforementioned problems.

** Code Notes

The main idea behind is to take a URL, fetch normalized details like title
and author based on the type of URL (Amazon, Goodreads, Open Library) and
then format the details.

Main entry points is ~org-books-add-url~, which takes a URL, finds a "detail
fetching" function corresponding to the type of URL, and then calls
~org-books-add-book~, which will format the book with those details.  You
can call ~org-books-add-book~ directly if you want, and manually provide a
title and author.

There are a couple of wrappers around ~org-books-add-url~:

 * ~org-books-cliplink~: fetched the URL from the clipboard.
 * ~org-books-add-isbn~: constructs an Open Library URL from a raw ISBN
   number.
