:PROPERTIES:
:ID:       cf7cd60d-76a4-4a7a-8ef0-fa1e4ad25999
:END:
#+date: [2025-08-30 Sat 15:43]
#+hugo_lastmod: [2025-08-30 Sat 15:43]
#+title: Niter Kibbeh (Ethiopian Spiced Butter)
#+filetags: :vegetarian:ethiopian:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Ethiopian spiced butter, used to make Misir Wat and other dishes

Source: https://www.daringgourmet.com/niter-kibbeh-ethiopian-spiced-clarified-butter/

Yield: 2 cups

** Ingredients

 * 1 pound unsalted butter, cubed
 * 1/4 cup chopped yellow onion
 * 3 tablespoons minced fresh garlic
 * 2 tablespoons minced fresh ginger
 * 1 2-inch cinnamon stick
 * 1 teaspoon whole black peppercorns
 * 3 BLACK cardamom pods (not the green cardamom variety)
 * 3 whole cloves
 * 1 teaspoon fenugreek seeds
 * 1 teaspoons coriander seeds
 * 1 teaspoon dried oregano
 * 1/2 teaspoon cumin seeds
 * 1/4 teaspoon ground nutmeg
 * 1/4 teaspoon ground turmeric
 * 1 tablespoon besobela ,if you can find it, otherwise omit (see blog post)
 * 1 tablespoon kosseret ,if you can find it, otherwise omit (see blog post)

** Instructions

Toast the whole spices over medium heat in a dry skillet for a few minutes
until very fragrant.  Be careful not to scorch the spices or they will
become bitter.  Set aside.

Place all the ingredients in a medium saucepan and bring it to an extremely
low simmer.  Continue to simmer over low for at least one hour or up to 90
minutes.  BE VERY CAREFUL NOT TO BURN THE BUTTER.  If it burns it will be
bitter and there is no salvaging it.

Pour everything through a fine-mesh cheesecloth.  (No need to skim off the
foam, everything will be removed during straining.) Pour the niter kibbeh
into a jar, let it cool, and cover so that it is airtight.  It will keep at
room temperature for several weeks, in the fridge for at least a couple of
months, and even longer in the freezer (it will be hard in the fridge and
freezer, let it come to room temp for easy scooping).  Makes about 2 cups.
