:PROPERTIES:
:ID:       c5922935-87b6-405d-9043-e0341b747f51
:END:
#+date: [2025-08-12 Tue 19:54]
#+hugo_lastmod: [2025-08-12 Tue 19:54]
#+title: Berbere Spice
#+filetags: :spices:ethiopian:vegetarian:vegan

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Yield: 18 servings

Source: https://www.daringgourmet.com/berbere-ethiopian-spice-blend/

I usually buy berber spice from my local ethnic organic grocer, but this is
still useful to have around in case I ever lose access to this place.  I
don't think it's quite authentic but would work in a pinch.
  
Yield: 18 servings

** Ingredients:
 * 2 teaspoons coriander seeds
 * 1 teaspoon cumin seeds
 * 1/2 teaspoon fenugreek seeds
 * 1 teaspoon black peppercorns
 * 2 whole allspice berries
 * Seeds of 4 green cardamom pods
 * 4 cloves
 * 5 dried red chilies , seeds and membranes removed and broken into small pieces (see Note)
 * 3 tablespoons sweet paprika
 * 1 teaspoon salt
 * 1/4 teaspoon nutmeg
 * 1/2 teaspoon ginger
 * 1/4 teaspoon cinnamon
 * 1 teaspoon turmeric

** Instructions

In a heavy skillet over high heat, toast the whole spices (seeds) and
chilies, shaking the pan regularly to prevent scorching, until very
fragrant, about 3 minutes. Transfer to a bowl and let cool completely.

Grind the cooled spices in a spice or coffee grinder. Add all remaining
ground spices and salt and grind everything together.

Store in an airtight container in a dark place.

NOTES

If you like extreme heat, leave a few of the seeds in. It will still be very
spicy even without the seeds.
