:PROPERTIES:
:ID:       1052934f-2104-4317-8d23-eb9e3f106a2d
:END:
#+date: [2025-01-26 Sun 22:00]
#+hugo_lastmod: 2025-01-28 08:37:27 -0500
#+title: Ox-hugo Exporter

An [[id:FA31BDBE-5F87-4DEE-ABE2-D8AFD52F7D03][org-mode]] exporter that I use to convert and [[id:4e639dc7-567a-408b-9ec1-c3f958958952][org-roam]] note cache into a
collection of Markdown files that can be made part of a [[id:07022b8a-cfe2-4b37-8e78-0844d3f57a5c][Hugo]] site or, with
some massaging, and [[id:0F0DCEA3-43C5-4396-AA23-8039242035F5][eleventy]] site.

One issue with using this exporter, indeed with any org exporter, is that it
doesn't really deal with a project.  You convert individual files.  So, for
example, when you're converting an org file to markdown, there's no notion
of preserving that path of the file in the output.

** Sections

With ox-hugo you specify the section that the post is going under, with
~org-hugo-section~

** Comparison with ox-html

The ox-hugo converter turns org files into Hugo flavoured markdown.  When
Hugo converts the markdown files into HTML, I've found that the there aren't
as many CSS hooks available in the HTML, as compared to the ox-html
converter which adds a bunch of wrapper divs which makes styling easier.

This is why my reading list isn't strictly part of my org-roam site.  My
org-roam notes are converted to HTML via markdown which is produced from
ox-hugo, and I find that getting the styles to do what I want is tougher in
that case.  So instead I use the ox-html converter and let then let Hugo
pass the HTML through.
