:PROPERTIES:
:ID:       55df4997-f4dc-4fdc-b747-93e6cafc5f1e
:END:
#+date: [2025-08-31 Sun 09:19]
#+hugo_lastmod: [2025-08-31 Sun 09:19]
#+title: Risotto
#+filetags: :italian:rice:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This is a good, reliable risotto recipe, amalgamated from various sources
I've found around the Internet

Yield: 4 servings

** Ingredients

 * 1/4 cup olive oil
 * One medium to large onion, minced
 * 3-4 cloves garlic, minced
 * 1 3/4 cups arborio rice
 * 6 cups boiling broth (chicken, vegetable, mushroom, etc.)
 * 3/4 cup Parmesan cheese
 * salt and pepper

** Instructions

Cook the onion in the olive oil until soft, about 8 minutes.  Add the
garlic, cook for 1-2 minutes.  Add the rice, and coat it until the cores
become visible.  Add a laddle-full of broth to the rice and cook until the
broth is absorbed.  Keep doing this until the broth is all absorbed (about
20-30 minutes).  Add the cheese, salt and pepper at the end to taste.

Variation: Mushroom Risotto: Fry about 2 cups of mushrooms in the olive pil
after the onion but before the garlic.  Add rice and continue as before.
