:PROPERTIES:
:ID:       4f7df4db-e80f-4a0a-98b2-9ef03b268f9e
:END:
#+date: [2025-08-30 Sat 08:45]
#+hugo_lastmod: [2025-08-30 Sat 08:45]
#+title: Lasagna (Vegetarian)
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

A relatively simple and healthy vegetarian lasagna that I've adapted from
various online sources.

Yield: 9 servings

** Ingredients

 * 1 jar (700ml) tomato sauce
 * 1 package (500g) cottage cheese
 * half of a 400g block of mozzarella cheese (i.e. 200 g of cheese), grated
 * 1/4 cup of Parmesan
 * 1 egg
 * 1 pint of mushrooms (227 g), sliced
 * half a standard block of tofu (TODO: get exact amount)
 * 6 balls of chopped, frozen spinach (TODO: get exact amount), defrosted and drained
 * 9 lasagna noodles

** Instructions

Boil lasagna noodles 10 minutes.

Make the cheese filling in a bowl by mixing cottage cheese, spinach, half
the mozzarella cheese, Parmesan, and egg.

Chop the tofu into small cubes.

Spread a small amount of the tomato sauce in the bottom of a lasagna pan.
Place 3 lasagna noodles in the pan, then more tomato sauce, then half the
cheese mixture, then half the mushrooms, and half the tofu.  Repeat the
layer: noodles, sauce, cheese mixture, mushrooms, tofu.  Add the final 3
noodles, the rest of the sauce, and sprinkle the rest of the mozzarella on
top.

Cover and bake at 375F for about 45 minutes.
