:PROPERTIES:
:ID:       aa772a01-2fce-43ae-a191-865bcf934c49
:END:
#+date: [2025-08-17 Sun 07:47]
#+hugo_lastmod: [2025-08-17 Sun 07:47]
#+title: Chicken Picatta
#+filetags: :chicken:italian:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Easy recipe, but pretty rich so I don't make it that often.  Still good for
a treat once in a while.

Source: http://vivalabuenavida.blogspot.com/2009/10/my-favorite-meal-chicken-picatta.html

Yield: 4 servings

** Ingredients
 * 4 boneless, skinless chicken breasts, pounded until thin.
 * 4 Tablespoons Olive Oil
 * 1/4 cup flour for dusting
 * 1/2 cup dry white wine
 * 2-4 teaspoons garlic, minced
 * 1 cup low-sodium chicken broth
 * 4 Tablespoons lemon juice
 * 2 Tablespoons capers, drained
 * 4 tablespoons butter
 * Fresh lemon slices

** Instructions

Season chicken with salt and pepper. Place flour into a Ziploc bag, and
insert chicken pieces one at a time to coat. Spray a saute pan with
non-stick spray then add vegetable oil and heat. Saute chicken 2-3 minutes
on one side, flip over and cook the other side 1-2 minutes with the pan
covered. Transfer cutlets to a plate, and place in the microwave or oven to
keep warm. Pour off fat from the pan. Deglaze the pan with white wine, and
add garlic. Cook until the garlic is slightly brown and the liquid is nearly
gone. Add broth, lemon juice, and capers. Return chicken to pan and cook one
more minute each side, or until juices run clear. Finish with a pat of
butter and lemon slices on each piece of chicken.
