:PROPERTIES:
:ID:       bdee69a9-1f36-4163-9052-9edbdf610a65
:END:
#+date: [2025-08-29 Fri 16:20]
#+hugo_lastmod: [2025-08-29 Fri 16:20]
#+title: Best Ever Creamy Crockpot Cocoa
#+filetags: :dessert:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Delicious but very rich.  I usually reserve this for the holidays, often New Year's Eve.

Source: http://www.onegoodthingbyjillee.com/2014/12/best-ever-creamy-crockpot-cocoa-an-ipad-mini-giveaway.html

Yield: 12 servings

** Ingredients
 * 1 1/2 cups heavy whipping cream
 * (1) 14 ounce can sweetened condensed milk
 * 6 cups milk
 * 1 1/2 teaspoons vanilla
 * 2 cups of chocolate chips (milk chocolate OR semi-sweet)

** Instructions

Pour all the ingredients into a crockpot and whisk together until well
combined. Cover and cook on low for 2 hours, stirring occasionally, until
mixture is hot and chocolate chips are melted. Whisk well before
serving. Garnish as desired (which means MARSHMALLOWS of course!)

From source:

> According to Amanda you can also make it with white chocolate,
butterscotch, even MINT chocolate chips! I DO love mint chocolate! The
possibilities here are vast! I’m thinking of maybe trying a salted caramel
version! Yummmm!
