:PROPERTIES:
:ID:       2fa2b796-f69e-4b15-b6f7-ac5b9e344f16
:END:
#+date: [2025-08-30 Sat 19:32]
#+hugo_lastmod: [2025-08-30 Sat 19:32]
#+title: Rice Pudding
#+filetags: :dessert:rice:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Rice pudding gets a bad rap, but I happen to like it, and this is one of the
better ones I've tried.

Source: http://allrecipes.com/recipe/27131/creamiest-rice-pudding/

Yield: 12 servings

** Ingredients

 * 2 litres milk, minus 1/4 cup for the egg mix
 * 1 cup white sugar
 * 1 cup uncooked long-grain white rice￼
 * 3 eggs, lightly beaten
 * 1/4 teaspoon salt￼
 * 2 teaspoons vanilla extract
  
** Instructions

In a large saucepan over medium-low heat, combine milk, sugar and rice.
Simmer, covered, 1 hour, stirring frequently. Remove pan from heat and let
rest 10 minutes.

In a small bowl, combine eggs, 1/4 cup milk, salt and vanilla. Stir into
rice mixture and return pot to low heat, stirring constantly, for 2
minutes. Pour into a 9x13 inch dish and cover with plastic wrap, folding
back the corners to allow the steam to escape.

When pudding has cooled to room temperature, remove plastic wrap and
sprinkle surface of pudding with cinnamon. Cover tightly (with fresh wrap)
and refrigerate 8 hours or overnight before serving.
