:PROPERTIES:
:ID:       c1a97a5f-82b8-4230-8d14-e11af384f8ef
:END:
#+date: [2025-08-30 Sat 08:50]
#+hugo_lastmod: [2025-08-30 Sat 08:50]
#+title: Lasagna (Jennifer's Version)
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This one comes from my friend Jennifer.

** Ingredients

 * 1 aubergine, cut into 1 cm cubes
 * 1 onion, diced
 * 1 clove garlic, crushed
 * 1 celery stalk, diced
 * 1 green pepper, seeded, diced
 * 2 courgettes, diced
 * 2 carrots, diced
 * 2 tbsp olive oil
 * 1 400g can diced tomatoes
 * 300 ml vegetable broth
 * 1 tbsp cornstarch
 * 1 tsp cold water
 * 4 tbsp chopped basil
 * 175 g cheddar, grated
 * 450 ml Greek yogourt
 * 1 egg, beaten
 * 12 sheets lasagna noodles
 * 50 g toasted pine nuts
 * pepper
 * salt

** Instructions

Put aubergine in a colander, sprinkle with salt. Let stand 30 mins. Rinse
then dry.

Fry onion, garlic and celery stalk in olive oil for 5 mins.

Add green pepper, courgettes, carrots and the aubergine and fry for 5
minutes.

Stir in tomatoes, vegetable stock, 3 tbsp chopped basil, salt and pepper,
cover and simmer for 30 minutes.
 
Blend corn starch with cold water, stir in and cook for 3 minutes.
 
Spoon a quarter of the vegetable sauce in a 1.2 litre ovenproof dish.
 
Sprinkle 25g of cheese over sauce and cover with 4 sheets of lasagne. Repeat
twice, spoon over rest of sauce.
 
Mix yogourt with 1 tbsp chopped basil, egg, 25g of the grated cheese, and
season with salt and pepper. Spread over the top, scatter over 50g lightly
toasted pine nuts and rest of cheese.
 
Bake at 200C/400F for 45 minutes
