:PROPERTIES:
:ID:       8950a7e5-5885-47a7-8448-0f5deb256205
:END:
#+date: [2025-08-29 Fri 16:33]
#+hugo_lastmod: [2025-08-29 Fri 16:33]
#+title: Endive Rice Soup
#+filetags: :endives:asian:vegetarian:vegan:soup:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Suprisingly simple and tasty.  Use good quality sesame oil.  You don't need
to use Japnaese rice.

Source: https://endive.com/recipes/Endive_Rice_Soup

Yield: 4 servings

** Ingredients

 * 1 tablespoon canola oil
 * 2 teaspoons toasted sesame oil
 * 3 cloves garlic, minced
 * 2 scallions, finely chopped
 * 1 tablespoon grated ginger
 * 1 teaspoon chili garlic sauce
 * 1/2 cup uncooked Japanese rice
 * 6 cups vegetable stock
 * 1 1/2 tablespoons soy sauce
 * 3 heads endive, roughly chopped and leaves separated
 * White pepper

** Instructions

Heat the canola and toasted sesame oils in a pot over medium heat. Add the
garlic and scallions and saute until fragrant.

Add the ginger and chili garlic sauce and cook for one minute.

Add the vegetable stock and soy sauce and bring to a boil. Then add the
rice. When the stock returns to a boil, cover the pot, then reduce the heat
to a simmer and let the soup cook until the rice is cooked through, about 30
minutes.

Add the endive and simmer the soup until the endive is tender and wilted,
about 6 minutes. Remove the pot from the heat, season with white pepper, and
serve.
