:PROPERTIES:
:ID:       a12b7f7c-05a1-4637-ad5d-41c2893fe041
:END:
#+date: [2025-08-30 Sat 18:52]
#+hugo_lastmod: [2025-08-30 Sat 18:52]
#+title: Popovers
#+filetags: :breakfast:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Make these for breakfast.  Good with jam.

Source: http://home.insightbb.com/~bonnett/popover/popover_recipe.htm

Yield: 6 popovers

** Ingredients

 * 1 cup sifted all-purpose flour
 * 1/2 teaspoon salt
 * 2 large eggs
 * 1 cup milk
  
** Instructions

Popovers rise by steam, and it's hard to get them right.  If you must follow
just one tip, make it this one: MAKE SURE THE INGREDIENTS ARE AT ROOM
TEMPERATURE.  Warm ingredients make for much better rising.

Preheat the oven to 450°F.

Mix together the flour and the salt in a LARGE bowl.

Whisk together the eggs and milk in a SMALL bowl.

Stir the liquid ingredients into the dry ingredients, stirring the batter
until just mixed.  Do not overmix.

Preheat a popover pan just until hot.  Brush the cups with melted butter and
fill them half full of batter.

Bake for 20 minutes at 450°F.  Turn the heat down to 375°F and bake for an
additional 20 minutes until they are a crispy golden brown.

Serve immediately.
