:PROPERTIES:
:ID:       d66fc5ed-bd9e-40b2-a916-7207e7908ac9
:END:
#+date: [2025-08-31 Sun 09:50]
#+hugo_lastmod: [2025-08-31 Sun 09:50]
#+title: Tonic Water (Jeffry Morgenthaler's Version)
#+filetags: :cocktails:softdrinks:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This is the classic tonic water recipe floating around the Internet. I
personally find it a bit complicated and the lemongrass puts me off but you
may like it better.

Source: http://www.jeffreymorgenthaler.com/2008/how-to-make-your-own-tonic-water/

Yield: 4 cups syrup

** Ingredients

 * 4 cups water
 * 1 cup chopped lemongrass (roughly one large stalk)
 * 1/4 cup powdered cinchona bark
 * zest and juice of 1 orange
 * zest and juice of 1 lemon
 * zest and juice of 1 lime
 * 1 tsp whole allspice berries
 * 1/4 cup citric acid
 * 1/4 tsp Kosher salt

** Instructions

Combine ingredients in a medium saucepan and bring to a boil over high
heat. Once mixture starts to boil, reduce heat to low, cover and simmer for
20 minutes.

Remove from heat and strain out solids using a strainer or chinois. You’ll
need to fine-strain the mixture, as it still contains quite a bit of the
cinchona bark. You can use a coffee filter and wait for an hour or more, or
do as I do and run the whole mixture through a French coffee press.

Once you’re satisfied with the clarity of your mix, heat it back up on the
stovetop or microwave, and then add 3/4 cup of agave syrup to each cup of
your hot mix. Stir until combined, and store in the attractive bottle of
your choice.

You now have a syrup that you can carbonate with seltzer water; I use my iSi
soda siphon for some nicely-textured bubbles. To assemble a gin and tonic,
use 3/4 ounce of syrup, 1 1/2 ounces of gin and 2 ounces of soda water over
ice.
