:PROPERTIES:
:ID:       6460faa8-0a38-4e4f-9c22-d3f058bef03f
:END:
#+date: [2025-08-31 Sun 09:47]
#+hugo_lastmod: [2025-08-31 Sun 09:47]
#+title: Tiramisu
#+filetags: :italian:dessert:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

The classic Italian dessert.  Very hard not to love.

Source: https://www.allrecipes.com/recipe/21412/tiramisu-ii/

Yield: 12 servings

** Ingredients

 * 6 egg yolks
 * 3/4 cup white sugar
 * 2/3 cup milk
 * 1 1/4 cups heavy cream
 * 1/2 teaspoon vanilla extract
 * 1 pound mascarpone cheese
 * 1/4 cup strong brewed coffee, room temperature
 * 2 tablespoons rum
 * 2 (3 ounce) packages ladyfinger cookies
 * 1 tablespoon unsweetened cocoa powder
  
** Instructions

Notes: for a stronger coffee flavour, double the coffee.  You can also get
away with using only one cup of the whipping cream, so you don't have to buy
a whole pint.

In a medium saucepan, whisk together egg yolks and sugar until well
blended. Whisk in milk and cook over medium heat, stirring constantly, until
mixture boils. Boil gently for 1 minute, remove from heat and allow to cool
slightly. Cover tightly and chill in refrigerator 1 hour.

In a medium bowl, beat cream with vanilla until stiff peaks form. Whisk
mascarpone into yolk mixture until smooth.

In a small bowl, combine coffee and rum. Split ladyfingers in half
lengthwise and drizzle with coffee mixture.

Arrange half of soaked ladyfingers in bottom of a 7x11 inch dish. Spread
half of mascarpone mixture over ladyfingers, then half of whipped cream over
that. Repeat layers and sprinkle with cocoa. Cover and refrigerate 4 to 6
hours, until set
