:PROPERTIES:
:ID:       0a9d6b2b-253a-44d2-aa57-54c58b0adb10
:END:
#+date: [2025-08-12 Tue 19:57]
#+hugo_lastmod: 2025-09-09 21:05:24 -0400
#+title: Big Apple Crumb Cake
#+filetags: :apples:cake:dessert:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Source: https://smittenkitchen.com/2021/10/big-apple-crumb-cake/

Yield: 16 servings

Hard to resist this one, and a delicious way to use up a some apples

** Ingredients:

*Apples*
 * 1 pound apples (3 medium or 2 large), peeled if you wish, cored, cut into 1/2-inch wedges
 * Juice of half a lemon
 * 1 teaspoon ground cinnamon
 * 1 tablespoon granulated sugar
   
*Crumbs*
 * 115 grams (1/2 cup) unsalted butter, melted
 * 65 grams (1/3 cup) light or dark brown sugar
 * 65 grams (1/3 cup) granulated sugar
 * 1 teaspoon ground cinnamon
 * 1/4 teaspoon kosher salt
 * 175 grams all-purpose flour
   
 *Cake*
 * 85 grams (6 tbsp) unsalted butter, softened
 * 100 grams (1/2 cup) granulated sugar
 * 1 large egg
 * 80 grams (1/3 cup) sour cream
 * 1 teaspoon (5 ml) vanilla extract
 * 130 grams (1 cup) all-purpose flour
 * 1 1/4 teaspoon baking powder
 * 3/4 teaspoon kosher salt
   
 *Finish*
 
 * Powdered sugar, for dusting

** Instructions

**Heat oven**: To 325°F (165°C). Lightly coat an 8-inch square or 9-inch
cake pan with butter or nonstick spray. For extra security, line it with
parchment paper.  Prepare apples: Toss apples with lemon juice, then
cinnamon and sugar and set aside.

**Make crumbs**: Whisk butter, sugars, cinnamon, and salt together until
evenly mixed. Add flour and mix until it disappears. It’s going to be very
thick; set it it aside.

**Make cake**: Beat butter with sugar until lightened and fluffy. Add egg,
sour cream, and vanilla and beat until combined. Sprinkle surface of batter
with with baking powder and salt, and beat well to combine. Add flour and
mix only until it disappears.

**Assemble**: Scrape batter into prepared cake pan and smooth it
flat. Arrange apples on cake, slightly overlapped. I usually fit all but 2
wedges; those are cook’s snacks. Pour any cinnamon-apple juices in bottom of
bowl over apples. Sprinkle crumbs over apple slices. For bigger crumbs,
squeeze the crumbs into small fistfuls and break these up into a couple
bigger chunks over the cake.

**Bake**: Bake the cake until a toothpick inserted into the apples doesn’t
hit any crisp spots and if you look closely, you’ll see juices bubbling
around some apples, about 50 to 55 minutes.

Cool to room temperature, if you can bear it, before cutting into squares or
wedges. Dust generously with powdered sugar.

Cake keeps at room temperature loosely covered (in an airtight container,
the crumbs eventually soften) for 3 days or in the fridge, well-wrapped, for
6 days.
