:PROPERTIES:
:ID:       72824270-1b58-4c79-9df3-abb1ee8ded14
:END:
#+date: [2025-08-29 Fri 16:39]
#+hugo_lastmod: [2025-08-29 Fri 16:39]
#+title: Gingerbread (Nigella Lawson's Version)
#+filetags: :dessert:cake:ginger:
  
[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

This one comes from Nigella Lawson.  More cake-y, less bread-y.  I've found
that it's actually not that sticky if you bake it for an extra 5 minutes.
If you don't have golden syrup you can use a mixture of corn syrup and
honey.

Source: https://www.styleathome.com/food-and-drink/recipes/article/recipe-nigella-s-sticky-gingerbread

Yield: 20 servings

** Ingredients

 * 150g butter
 * 200g golden syrup
 * 200g black treacle or molasses
 * 125g dark muscovado sugar
 * 2 teaspoons finely grated ginger
 * 1 teaspoon ground ginger
 * 1 teaspoon ground cinnamon
 * 1/4 teaspoon ground cloves
 * 1 teaspoon bicarbonate of soda, dissolved in 2 x 15ml tablespoons warm water
 * 250ml full-fat milk
 * 2 eggs, beaten to mix
 * 300g plain flour

** Instructions

Preheat the oven to 170°C/gas mark 3 and line a roasting tin or ovenproof
dish (approx. 30cm x 20cm x 5cm) with Bake-O-Glide, foil or baking parchment
(if using foil, grease it too).

In a saucepan, melt the butter over a lowish heat along with the sugar,
syrup, treacle, fresh and ground gingers, cinnamon and cloves.

Take off the heat, and add the milk, eggs and dissolved bicarbonate of soda
in its water.

Measure the flour into a bowl and pour in the liquid ingredients, beating
until well mixed. It will be a very liquid batter, so don’t worry. This is
part of what makes it sticky later.

Transfer the tin to a wire rack and let the gingerbread cool in the tin
before cutting into 20 squares, or however you wish to slice it.

Pour it into the prepared tin and bake for 45–60 minutes until risen and
firm on top. Try not to overcook, as it is nicer a little stickier, and
anyway will carry on cooking as it cools.

