:PROPERTIES:
:ID:       d6ac2d1c-f12e-41c5-8cd3-b9b05cafe8c3
:END:
#+date: [2025-08-31 Sun 17:21]
#+hugo_lastmod: [2025-08-31 Sun 17:21]
#+title: Orange Liqueur
#+filetags: :cocktail:vegetarian:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

A decent replacement for Triple Sec in cocktails

Source: http://www.cbc.ca/inthekitchen/mobile/touch/blog/2012/12/homemade-orange-liqueur.html

Yield: 4.5 cups

** Ingredients

 * Peel of 5 to 6 oranges, such as 1 regular orange and 4 to 5 clementines
   or mandarins
 * 2 cinnamon sticks
 * 1 tbsp. coriander seeds
 * 2 1/2 cups of vodka
 * 2 cups sugar
 * 2 cups water

** Instructions

Notes: I let the peels soak in the vodka for two weeks, not two days.

Add orange peels, cinnamon sticks, coriander seeds and vodka to a mason
jar. Seal and let steep for 2 days in cool place.

Strain vodka through fine mesh strainer to remove peel and spices. Set
aside.

Heat water and sugar until sugar just dissolves. Let cool completely. Add
this simple syrup to the vodka mixture. Stir to combine.

Using a funnel, pour liqueur into a bottle. Add cork and seal. Let the
liqueur sit for at least two weeks and then 1 week in the fridge. Keep
refrigerated and serve cold.
