:PROPERTIES:
:ID:       4e639dc7-567a-408b-9ec1-c3f958958952
:END:
#+date: [2025-01-03 Fri 20:15]
#+hugo_lastmod: 2025-01-19 21:49:46 -0500
#+title: Org Roam

A rudimentary roam replication in [[id:FA31BDBE-5F87-4DEE-ABE2-D8AFD52F7D03][org mode]] and [[id:e8f63911-0c0b-4f37-9aed-b2e415144f9d][Emacs]].

Used for implementing general note taking and Zettelkestan.

https://blog.jethro.dev/posts/introducing_org_roam/
https://blog.jethro.dev/posts/capturing_inbox/
https://blog.jethro.dev/posts/processing_inbox/
https://blog.jethro.dev/posts/zettelkasten_with_org/
https://blog.jethro.dev/posts/introducing_org_roam/

** Why org roam?

Why org-roam and not something like Roam Research?

 * You can leverage the power of [[id:e8f63911-0c0b-4f37-9aed-b2e415144f9d][Emacs]] and [[id:FA31BDBE-5F87-4DEE-ABE2-D8AFD52F7D03][Org Mode]] but maybe more
   importantly
 * You can store all your notes in [[id:a2e09732-e1f9-4e01-a5fa-74092ae75cd5][plain text]] which means there's a better
   chance they will last longer

This is especially important for something like a Zettelkasten, which is
supposed to be a life long companion, with your notes lasting years, maybe
even decades.  Do we think Roam Research will be around 30 years from now?
Emacs and plain text will be.

** How to take smart notes with org mode
https://blog.jethro.dev/posts/how_to_take_smart_notes_org/

Good quote here:

#+begin_quote
The primary purpose of note-taking should not be for storing ideas, but for
developing them. When we take notes, we should ask: “In what context do I
want to see this note again?”
#+end_quote

 * Fleeting notes (random thoughts) are taken on the daily notes

** How I take notes with org-roam   
https://jethrokuan.github.io/org-roam-guide/

Uses slip boxes:

 * reference
 * main
 * articles (not really interested in this)

He also uses an inbox, which I guess could just be my [[id:c1c6678a-b2cc-4b5c-96cd-5edc22666ab0][GTD]] inbox.

Reference notes have a ROAM_REF key, which comes in two flavours:

 * [cite:key] for books
 * the URL for websites

I am unclear what cite:key is supposed to mean, but this may have something
to do with org-ref.

Everything has draft tag until they don't.
