:PROPERTIES:
:ID:       391f7d8a-2c03-40dd-89ae-08836f827b71
:END:
#+date: [2025-08-30 Sat 14:52]
#+hugo_lastmod: [2025-08-30 Sat 14:52]
#+title: Meatloaf (Vegetarian)
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Being vegetarian, this is obviously not a real meatloaf, but it's still
pretty good.

Source: http://www.food.com/recipe/really-good-vegetarian-meatloaf-really-33921

Yield: 4-6 servings

** Ingredients

 * 2 cups water
 * 1 teaspoon salt
 * 1 cup lentils
 * 1 small onion, diced
 * 1 cup quick-cooking oats
 * 3/4 cup grated cheese (Cheddar, Swiss, Monterey Jack, or American)
 * 1 egg, beaten
 * 4 1/2 ounces tomato sauce
 * 1 teaspoon garlic powder
 * 1 teaspoon dried basil
 * 1 tablespoon dried parsley
 * 1/2 teaspoon seasoning salt
 * 1/4 teaspoon black pepper
  
** Instructions

Add salt to water and boil in a saucepan.

Add lentils and simmer covered 25-30 minutes, until lentils are soft and
most of water is evaporated.  Remove from fire.

Drain and partially mash lentils.
 
Scrape into mixing bowl and allow to cool slightly.

Stir in onion, oats and cheese until mixed.

Add egg, tomato sauce, garlic, basil, parsley, seasoning salt and pepper.
Mix well.

Spoon into loaf pan that has been generously sprayed with Pam (non-stick
cooking spray) or well-greased.

Smooth top with back of spoon.

Bake at 350 degrees for 30-45 minutes until top of loaf is dry, firm and
golden brown.

Cool in pan on rack for about 10 minutes.

Run a sharp knife around edges of pan then turn out loaf onto serving
platter.
