:PROPERTIES:
:ID:       7f49c7f8-4b89-465b-b793-0c81138b5aac
:END:
#+date: [2026-09-04 Fri 21:59]
#+hugo_lastmod: [2026-09-04 Fri 21:59]
#+title: Caramel Apple Cake
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Scrumptious, though a bit long to make.  The recipe is for three 6-inch
cakes but two 8-inch cake work.  Two 9-inch cakes also work, but not as
well.

Source: https://livforcake.com/caramel-apple-cake/

Yield: 1 cake

** Ingredients

*Apples*
 * 2 cups diced apples (heaping, approx. 2 medium apples)
 * 1 tablespoon light brown sugar
 * 1 teaspoon ground cinnamon

*Apple Spice Cake*
 * 2 cups all-purpose flour
 * 2 teaspoons baking powder
 * 3/4 teaspoon salt
 * 1 1/2 teaspoons ground cinnamon
 * 3/4 teaspoon ground nutmeg
 * 1 cup vegetable oil
 * 1/2 cup light brown sugar, packed
 * 1 cup granulated sugar
 * 3 large eggs, room temperature
 * 1 teaspoon vanilla extract

*Caramel*
 * 1 cup granulated sugar
 * 1/4 cup water
 * 150 ml heavy cream, room temperature
 * 1/2 cup unsalted butter, room temperature

*Caramel Swiss Meringue Buttercream*
 * 3 large egg whites
 * 1 cup granulated sugar
 * 1 cup unsalted butter, room temperature, cubed
 * 1/2 cup caramel

** Instructions

*** Apples

Peel and dice the apples. Toss in 1 tablespoon light brown sugar and
1 teaspoon cinnamon. Set aside.

*** Apple Spice Cake

Preheat oven to 350°F. Grease and flour three 6-inch cake rounds, line
with parchment.

In a medium bowl, combine flour, baking powder, spices, and salt. Set aside.

In the bowl of a stand mixer combine vegetable oil and sugars. Beat until
well combined (2 mins). Add eggs one at a time, fully incorporating after
each addition. Add vanilla.

Add flour mixture in 3 parts. Fold in apples.

Spread batter evenly into prepared pans and bake for 45-50 mins or until a
toothpick inserted into the center comes out mostly clean.

Place cakes on wire rack to cool for 10mins then turn out onto wire rack to
cool completely.

*** Caramel

Place sugar and water into a medium pot, stir to combine, but do not stir
from this point forward. Cook over high heat, washing down the sides of the
pot with a pastry brush dipped in water as needed to prevent crystals.

Cook until desired color of caramel is reached (amber) and immediately
remove from heat. Very slowly pour in heavy cream while whisking quickly.
The mixture will bubble up (a lot) and boil. Add butter, return to heat,
and bring back to a boil. Cook for 2 minutes whisking constantly.

Remove from heat and let cool to room temperature. Transfer to a container
and place in fridge to thicken.

*** Caramel Swiss Meringue Buttercream

Place egg whites and sugar into the bowl of a stand mixer, whisk until
combined.

Place bowl over a hot water bath on the stove and whisk constantly until the
mixture reads 160°F on a candy thermometer and is no longer grainy to the
touch (approx. 3mins).

Place bowl on your stand mixer and whip on med-high until the meringue is
stiff and cooled (the bowl is no longer warm to the touch, approx. 5-10mins).

Switch to paddle attachment. Slowly add cubed butter and mix until smooth.

Add cooled caramel and whip until smooth.

*** Assembly

Trim cake layers if needed. Place one layer of cake on a cake stand or
serving plate. Top with 2/3 cup of frosting, spread evenly. Repeat with
remaining layers.

Frost and smooth the outside with a thin crumb coat. Chill for 20mins.

Using a small spoon, place dollops of caramel around the top edges of the
cooled cake, allowing some to drip down. Fill in the top of the cake with
more caramel and spread evenly with an offset spatula.

** Notes

- The caramel can be made the day before and left in the fridge overnight.
- Ensure there is NO trace of egg yolks in your whites and that your mixer
  bowl and whisk is completely grease free or your meringue won't stiffen.
- The buttercream may look like it's curdled at some point. Keep mixing
  until it is completely smooth.
- If caramel has thickened too much, microwave in 5-10 second intervals
  until it's pourable (but not warm).
