:PROPERTIES:
:ID:       1f931925-40d7-48a1-8923-adb100b0037a
:END:
#+date: [2026-07-01 Wed 11:34]
#+hugo_lastmod: [2026-07-01 Wed 11:34]
#+title: French Apple Cake
#+filetags:

[[id:3a1caf2c-7854-4cf0-bb11-bb7806618c36][Recipes]]

Simple and Delicious

Source: https://www.recipetineats.com/french-apple-cake-recipe/

Yield: 8-10 servings

** Ingredients
 * 3 red apples, peeled and diced into 1.5cm/0.6" cubes (~ 3 1/2 cups)
 * 100g (7 tbsp) unsalted butter, softened
 * 3/4 cup sugar
 * 3 large eggs, at room temperature
 * 1 tsp pure vanilla extract
 * 1 1/3 cups plain flour
 * 1 1/4 tsp baking powder
 * 1/4 tsp kosher salt

** Instructions

Preheat the oven to 180°C/350°F (160°C fan-forced).

Butter a 23cm/9" round cake pan and line the base with baking paper /
parchment paper. No need to line the sides.

In a separate bowl, whisk together the flour, baking powder and salt.

Using a handheld beater or stand mixer with the paddle attachment, beat the
butter for 1 minute on medium until creamed. Add the sugar and beat on
medium for 1 minute until fluffy and becomes a paler yellow.

Add the eggs one at a time, mixing well after each addition. Beat in the
vanilla extract.

Add the flour mixture into the bowl and beat on low until you can no longer
see dry flour, then stop beating. You don't want to overmix.

Stir through the diced apples using a spatula. The batter will be quite
thick, it's not pourable.

Spread the batter evenly into the prepared cake pan. Bake for 35 minutes, or
until a skewer inserted in the centre comes out clean (because the batter is
quite thick and if your oven runs a bit cool, it could take up to 45
minutes).

Let the cake rest for 5 minutes in the pan before removing. Cool for a
further 10 minutes then serve warm or let it cool completely on a wire
rack. Dust with icing sugar, if desired. If serving warm, it's especially
lovely with a scoop of ice cream.
