:PROPERTIES:
:ID:       a091822b-376b-43d6-9e0d-3742b0ecd95c
:END:
#+date: [2024-07-09 18:16]
#+title: Start here

Welcome to [[https://desmondrivet.com/about][my]] [[id:E9DDE472-8D71-4547-992C-56D16AE6A5E5][digital garden]], a repository for notes, reviews, recipes and
whatever else strikes my fancy.  Though you are, of course, welcome to
explore (this site wouldn't be public otherwise), I wrote these notes with
only myself in mind, so you may not get much use out of them.

This garden is generated with [[id:07022b8a-cfe2-4b37-8e78-0844d3f57a5c][Hugo]] via an [[id:4e639dc7-567a-408b-9ec1-c3f958958952][Org Roam]] note repository.

This [[id:E9DDE472-8D71-4547-992C-56D16AE6A5E5][digital garden]] has a number of "node communities" or "jumping off
points":

 * I have a smattering of [[id:0AC9298C-1F59-4518-8E3B-00EE144A3AF4][Daily notes]].  Look at the backlinks on that node
   to find them all.
 * I'm an [[id:e8f63911-0c0b-4f37-9aed-b2e415144f9d][Emacs]] user, and I've accumulated a number of notes on that subject
 * I have an interest in [[id:CAA54188-C8EF-4204-AB47-90A27514E2E8][personal information management (pim)]]
 * I like cooking and drinking, so I have a [[id:35EC8663-3548-4E1F-9A94-AE8FB8D7B5E7][food and drink]] page.
 * I run Linux at home and so I have a [[id:9b39db1c-a987-4a6f-8d3b-4d0cc2596867][Linux Administration]] page
 * [[id:74fe4896-3281-4665-8051-556ce8eca8b5][Software Development]]
 * [[id:073f104c-8e48-44a6-8f5f-81e5e89b4881][Blogging]]

I also have a page for [[id:296E9CFB-967A-495D-B99A-EE62BCC72244][orphaned or unlinked]] notes as well.
